### ISSUE TITLE
nextjs error Module build failed: TypeError:  Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by dtmkeng** [airbnb/react-dates#1031]
Nextjs error import 'react-dates/lib/css/_datepicker.css'
```
 at PluginPass.exit (/home/loserpop/dev/project/node_modules/babel-plugin-inline-import/build/index.js:29:48)
    at newFn (/home/loserpop/dev/project/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/loserpop/dev/project/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/loserpop/dev/project/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/loserpop/dev/project/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/home/loserpop/dev/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/loserpop/dev/project/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/loserpop/dev/project/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/loserpop/dev/project/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/home/loserpop/dev/project/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/loserpop/dev/project/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/loserpop/dev/project/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/loserpop/dev/project/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/loserpop/dev/project/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/home/loserpop/dev/project/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/home/loserpop/dev/project/node_modules/babel-core/lib/transformation/file/index.js:548:35)
```
```
import 'react-dates/initialize'
import React, { Component } from 'react'

import 'react-dates/lib/css/_datepicker.css'

import { DateRangePicker } from 'react-dates'
```

**Comment by ljharb** [comment]
I’m not sure what next.js is, but this stack trace implies you’re babel-transpiling 3rd party code, which is generally considered a bad practice.

Specifically, you’re importing a css file - what are you using to make that work,

**Comment by markolofsen** [comment]
Still not work

**Comment by ljharb** [comment]
I'm going to close this, since the ability to import CSS is nonstandard, and unrelated to react-dates.
