### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by AiusDa** [airbnb/react-dates#1132]
I am currently trying to implement react-dates in a project with Next, however I am having the following error:

```
window is not defined
ReferenceError: window is not defined
    at /Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/index.js:221:17
    at /Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/node_modules/react-dates/lib/css/_datepicker.css?15fb:36:1
    at module.exports.../node_modules/style-loader/lib/addStyles.js.module.exports (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/node_modules/style-loader/lib/addStyles.js?04ca:43:1)
    at Object.../node_modules/react-dates/lib/css/_datepicker.css (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/index.js:173:94)
    at __webpack_require__ (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/webpack/bootstrap 6bc0fd36a57b77837784?7b8c:22:1)
    at Object../components/Search/partials/Calendar/DateRangePicker/index.tsx (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/components/Search/partials/AutocompletePlaces.tsx?892b:27:13)
    at __webpack_require__ (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/webpack/bootstrap 6bc0fd36a57b77837784?7b8c:22:1)
    at Object../components/Search/index.tsx (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/node_modules/style-loader/lib/urls.js?0d14:9:1)
    at __webpack_require__ (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/webpack/bootstrap 6bc0fd36a57b77837784?7b8c:22:1)
    at Object../pages/index/sections/HomeBanner.tsx (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/pages/index/index.tsx?1de7:16:1)
    at __webpack_require__ (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/webpack/bootstrap 6bc0fd36a57b77837784?7b8c:22:1)
    at Object../pages/index/index.tsx (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/index.js:3020:91)
    at __webpack_require__ (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/webpack/bootstrap 6bc0fd36a57b77837784?7b8c:22:1)
    at Object.2 (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/index.js:4598:30)
    at __webpack_require__ (/Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/webpack:/webpack/bootstrap 6bc0fd36a57b77837784?7b8c:22:1)
    at /Users/adrian/Projects/CMM/cmm-front-react/build/dist/bundles/pages/index.js:77:25
```

I tried to resolve validating if render is on the server to avoid the error:

```
export function isServer(): boolean {
  return typeof window === 'undefined' ? true : false;
}
...
{ isServer() ? null : <DateRangePicker /> }
```

"moment": "^2.22.1"
"next": "^5.1.0"
"react": "^16.2.0"
"react-dates": "^16.6.1"

**Comment by majapw** [comment]
Does your solution address the issue?

**Comment by AiusDa** [comment]
No, the problem persists

**Comment by AiusDa** [comment]
In fact is a issue from style-loader with SSR, I'm trying to solve this with the best solution.

**Comment by ljharb** [comment]
In that case I'm going to close this issue; please post here if you find a solution, so others can benefit :-)
