### ISSUE TITLE
react-dates style overflows

### ISSUE THREAD

**Issue by MFry** [airbnb/react-dates#1269]
`DateRangePicker`'s `DateInput` components overflow the component. The **from** component seems to overflow the arrow in between the components and the **to** component overflows the main box. 
### Demo
![react-dates](https://user-images.githubusercontent.com/579618/42904702-4d8bba70-8a82-11e8-9dd4-f64c062656cb.gif)

### To reproduce:
Create a new project with [CRA](https://github.com/facebook/create-react-app) add

> npm install --save react-dates moment@>=#.## react@>=#.## react-dom@>=#.##

or clone the repo from the docs

> To see this in action, you can check out https://github.com/majapw/react-dates-demo which adds react-dates on top of a simple create-react-app setup.

Once the project is ready and dependencies are set change the `App.js` file:

```js
import React, { Component } from "react";
import "./App.css";

import "react-dates/initialize";
import "react-dates/lib/css/_datepicker.css";
import { DateRangePicker } from "react-dates";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      startDate: null,
      endDate: null,
      focusedInput: null
    };
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <DateRangePicker
            startDateId="startDate"
            endDateId="endDate"
            startDate={this.state.startDate}
            endDate={this.state.endDate}
            onDatesChange={({ startDate, endDate }) => {
              this.setState({ startDate, endDate });
            }}
            focusedInput={this.state.focusedInput}
            onFocusChange={focusedInput => {
              this.setState({ focusedInput });
            }}
          />
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
```

**Comment by MFry** [comment]
I have been able to isolate the bug and I believe I found what needed to be fixed it in the code, but I can't seem to figure out how to build and run the code from the repo.  I assumed `build` would do it, but that only seems to build the css. `npm run react` while impressive in size crashes after a while, so I am out of options.

**Comment by MFry** [comment]
@ljharb If you are able, could you let me know what I need to run to get `/lib` to populate. I know initialize and index.js are looking for files within it, but nothing looked obvious that would build the `lib/initialize` folder and the rest.

`npm run react` issue:
```bash
$ node -v 
v8.11.2
```
**The error:**
```
npm install enzyme-adapter-react-16@1.1.1 enzyme@^3.0.0 react@^16.0.0-0 react-dom@^16.0.0-0 --no-save

npm ERR! code ETARGET
npm ERR! notarget No matching version found for react@16.0.0-0
```
It might have something to do with windows? But the error doesn't suggest it does and my goal was to build it and be able to import it so that command I can do by hand.

**Comment by ljharb** [comment]
`npm run build` should do it, but yes, it very much might have something to do with windows. what does `npm --version` print out?

**Comment by MFry** [comment]
```bash
$ npm --version
6.2.0
```
Some more info from the logs
```
12 info lifecycle react-dates@17.1.1~react: Failed to exec react script
13 verbose stack Error: react-dates@17.1.1 react: `enzyme-adapter-react-install 16`
13 verbose stack Exit status 16
13 verbose stack     at EventEmitter.<anonymous> (C:\ProgramData\nvm\v8.11.2\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\ProgramData\nvm\v8.11.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid react-dates@17.1.1
```

**Comment by ljharb** [comment]
that specific exit code happens when `install-peerdeps -S enzyme-adapter-react-16` fails. Can you try running that command, by itself? If you're on windows, `npx install-peerdeps -S enzyme-adapter-react-16` may not work, in which case, you'd do `npm install --no-save install-peerdeps; ./node_modules/.bin/install-peerdeps -S enzyme-adapter-react-16`, i believe

**Comment by MFry** [comment]
@ljharb I think I isolated the issue. `npx install-peerdeps -S enzyme-adapter-react-16` works fine on windows, but the issue can be isolated to two parts of the code.
```bash
$ npm install react@^16.0.0-0

npm ERR! code ETARGET
npm ERR! notarget No matching version found for react@16.0.0-0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
and
```bash
$ npm install react-dom@^16.0.0-0

npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-dom@16.0.0-0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
The `npx install-peerdeps -S enzyme-adapter-react-16` command evaluates to `npm install enzyme-adapter-react-16@1.1.1 enzyme@^3.0.0 react@^16.0.0-0 react-dom@^16.0.0-0 --no-save`
If we fix that by removing the `-0` 
```bash
$ npm install enzyme-adapter-react-16@1.1.1 enzyme@^3.0.0 react@^16.0.0 react-dom@^16.0.0 --no-save
```
npm runs and installs the dependencies fine.

**Comment by ljharb** [comment]
What happens if the full package+version string is quoted?

The -0 is necessary to allow for prerelease versions, and is a valid part of the semver range.

**Comment by MFry** [comment]
If its quoted, it successfully runs.

> The -0 is necessary to allow for prerelease versions...
That's interesting! I did not know that it would work like that.

**Comment by ljharb** [comment]
In that case, can you file an issue on https://github.com/nathanhleung/install-peerdeps about this? Once patched, this issue will be resolved (I'm going to close it now, but please link the issue once filed).

**Comment by ljharb** [comment]
Oops, this issue is about something else :-) i'm going to reopen and hide all the somewhat offtopic discussion.

**Comment by Cr0cky** [comment]
So what was the problem? I have the exact same problem.

**Comment by mmarkelov** [comment]
@dimalakh @Cr0cky @MFry 
You should manually add to you css:
```css
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```
Note: This component assumes **box-sizing: border-box** is set globally in your page's CSS.

**Comment by MartinConde** [comment]
I've got the box-sizing set but it still cuts it off for me. Tried adding it to a blank page with no styles whatsoever to see if my own css was interfering but no dice. Got the most barebones implementation possible so nut sure what I'm still missing. Any pointers would be much appreciated.

![daterange](https://user-images.githubusercontent.com/34409953/142973203-6567871e-4bf1-4d3f-aa44-286c0eb63451.png)

**Comment by MartinConde** [comment]
Think I found the solution, adding `daySize={70}` seems to do the trick. Might have to play with the value but at least it doesn't get cut off anymore
