### ISSUE TITLE
Import react-dates causes error during testing

### ISSUE THREAD

**Issue by Karine91** [airbnb/react-dates#1282]
Hello, I'm trying write test for my react component, and it's fail when import 'react-dates'. What am I doing wrong?

> import React from 'react';
> import { shallow } from 'enzyme';
> import ExpenseDashboardPage from '../../components/ExpenseDashboard';
> 
> test('should render ExpenseDashboardPage', () => {
>     const wrapper  = shallow(`<ExpenseDashboardPage />`);
>     expect(wrapper).toMatchSnapshot();
> });

● Test suite failed to run

    TypeError: Object.values is not a function

      1 | import React from 'react';
      2 | import moment from 'moment';
    > 3 | import { SingleDatePicker } from 'react-dates';
        | ^
      4 |
      5 | export default class ExpenseForm extends React.Component {
      6 |     constructor(props) {

      at Object.<anonymous> (node_modules/react-outside-click-handler/build/OutsideClickHandler.js:42:48)
      at Object.<anonymous> (node_modules/react-outside-click-handler/index.js:2:18)
      at Object.<anonymous> (node_modules/react-dates/lib/components/DateRangePicker.js:40:33)
      at Object.<anonymous> (node_modules/react-dates/lib/index.js:46:24)
      at Object.<anonymous> (node_modules/react-dates/index.js:2:18)
      at Object.<anonymous> (src/components/ExpenseForm.js:3:1)
      at Object.<anonymous> (src/tests/components/ExpenseForm.test.js:3:1)

**Comment by ljharb** [comment]
This is a bug in react-outside-click-handler; I'll fix it there.

**Comment by Karine91** [comment]
Thank

**Comment by ljharb** [comment]
react-outside-click-handler v1.2.1 has been released.

**Comment by Karine91** [comment]
Hi, can you please fix dependencies for react-dates and set it to last version of react-outside-click-handler? Modules are reinstalled and tests failed again...

**Comment by ljharb** [comment]
@Karine91 the fixed version is included in the semver range, so no new publish is needed.

**Comment by Karine91** [comment]
I used the yarn, now reinstalled with npm and it's worked
