### ISSUE TITLE
How to make snapshot tests work

### ISSUE THREAD

**Issue by nicolasrouanne** [airbnb/react-dates#1366]
I'm using _Jest_ for testing and I try to make **_snapshot_ tests** of components rendering a `DayPickerRangeController` (although I guess this issue would be the same for other date pickers).

Say I **want to make a snapshot test of a simple component wrapping `DayPickerRangeController`**; used for setting nice defaults for instance, in my example `numberOfMonths`, `startDateOffset` and `endDateOffset`.
```js
import React from "react";
import moment from "moment";
import PropTypes from "prop-types";
import momentPropTypes from "react-moment-proptypes";
import "react-dates/initialize";
import { START_DATE, END_DATE } from "react-dates/constants";
import { DayPickerRangeController } from "react-dates";

const DayPickerRangeControllerWrapper = ({
  startDate,
  endDate,
  focusedInput,
  onDatesChange,
  onFocusChange
}) => (
  <DayPickerRangeController
    startDate={startDate}
    endDate={endDate}
    onDatesChange={onDatesChange}
    focusedInput={focusedInput}
    onFocusChange={onFocusChange}
    numberOfMonths={1}
    startDateOffset={day => day.clone().add(1, "day")}
    endDateOffset={day => day.clone().subtract(1, "day")}
  />
);

DayPickerRangeControllerWrapper.propTypes = {
  startDate: momentPropTypes.momentObj,
  endDate: momentPropTypes.momentObj,
  focusedInput: PropTypes.oneOf([START_DATE, END_DATE]),
  onDatesChange: PropTypes.func.isRequired,
  onFocusChange: PropTypes.func.isRequired
};

DayPickerRangeControllerWrapper.defaultProps = {
  startDate: moment("2018-01-01"),
  endDate: moment("2018-01-07"),
  focusedInput: START_DATE
};

export default DayPickerRangeControllerWrapper;
```

I then try to _snapshot test_ it
```js
import React from "react";
import renderer from "react-test-renderer";
import DayPickerRangeControllerWrapper from "./DayPickerRangeControllerWrapper";

describe("DayPickerRangeControllerWrapper", () => {
  it("renders correctly", () => {
    const tree = renderer
      .create(
        <DayPickerRangeControllerWrapper
          onDatesChange={() => {}}
          onFocusChange={() => {}}
          onClearDates={() => {}}
        />
      )
      .toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

I get the following error
```
TypeError: Cannot read property '__consolidated_events_handlers__' of null

      at addEventListener (node_modules/consolidated-events/lib/index.js:22:14)
      at CalendarMonthGrid.componentDidMount (node_modules/react-dates/lib/components/CalendarMonthGrid.js:215:77)
```

This seems to be somehow related to https://github.com/airbnb/react-dates/issues/528, but I haven't found a way to properly (and simply) mock `ReactDOM` or `CalendarMonthGrid` (that doesn't seem like a good way to go though).
I could **always _unit test_ my _wrapper_ component, but I would like to be able to _snapshot test_ it as well**.

**Comment by ljharb** [comment]
Altho i don’t recommend snapshot testing., I’d use ensyme’s .debug() method.

**Comment by nicolasrouanne** [comment]
@ljharb Can you explain why? 
Because _snapshot testing_ allows to quickly see changes on output of components **and have a diff commited to source control**, which I don't see in _enzyme_'s `.debug()`.

**Comment by ljharb** [comment]
You could compare two debug calls - the reason tho is because snapshot testing is inherently brittle. All it really tells you is “something changed”, which is only useful when attempting to do a no-change refactor, which is uncommon. When the snapshots differ, in practice it’s very hard to know what changed, why, and whether it’s important - so in practice, people just rubber stamp the diffs and there’s no benefit to be had.

Tests should be explicit, and assert on what’s importwnt. “Nothing changed” is rarely important when *making changes*.
