### ISSUE TITLE
SPFX JS Modern Calendar is not executing the second step - Gulp Serve

### ISSUE THREAD

**Issue by sarwan39** [airbnb/react-dates#1811]
SPFX JS Modern Calendar is not executing the second step - Gulp Serve

Attached the log file which got generated
[2019-09-27T19_09_18_575Z-debug.log](https://github.com/airbnb/react-dates/files/3664252/2019-09-27T19_09_18_575Z-debug.log)

**Error message:** 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\ppilli\Downloads\sp-dev-fx-webparts-master\s
p-dev-fx-webparts-master\samples\js-modern-calendar\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ljharb** [comment]
This is unrelated to react-dates; it looks like you're depending on a module that you don't have installed.
