### ISSUE TITLE
Error: Cannot find module 'react/lib/CSSPropertyOperations'

### ISSUE THREAD

**Issue by leebenson** [airbnb/react-dates#194]
Ran into this this morning (after nuking `node_modules` and re-installing, so I'm not _exactly_ sure where this was introduced):

Installing with the usual:
```sh
  (
    export PKG=react-dates;
    npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g; s/ *//g' | xargs npm install --save "$PKG"
  )
```

... when running my bundle, I now get:

> Error: Cannot find module 'react/lib/CSSPropertyOperations'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/leebenson/dev/<private>/node_modules/react-portal/build/portal.js:17:30)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/leebenson/dev/<private>/node_modules/react-dates/lib/components/DateRangePicker.js:942:19)
    at __webpack_require__ (/Users/leebenson/dev/<private>/node_modules/react-dates/lib/components/DateRangePicker.js:21:30)
    at Object.<anonymous> (/Users/leebenson/dev/<private>/node_modules/react-dates/lib/components/DateRangePicker.js:80:21)
    at __webpack_require__ (/Users/leebenson/dev/<private>/node_modules/react-dates/lib/components/DateRangePicker.js:21:30)

**Comment by leebenson** [comment]
ah, saw this in #188, closing...
