### ISSUE TITLE
Can't run live playground

### ISSUE THREAD

**Issue by sseppola** [airbnb/react-dates#2]
After running "npm install" i get errors when trying to run the storybook.

This is the errors I get:
```
ERROR in multi preview
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/sindre/projects/experiments/react-dates
 @ multi preview

ERROR in ./~/@kadira/storybook/dist/client/preview/index.js
Module not found: Error: Cannot resolve module 'redux' in /Users/sindre/projects/experiments/react-dates/node_modules/@kadira/storybook/dist/client/preview
 @ ./~/@kadira/storybook/dist/client/preview/index.js 42:13-29


ERROR in ./src/svg/arrow-right.svg
Module build failed: ReferenceError: Unknown plugin "syntax-jsx" specified in "base" at 0, attempted to resolve relative to "/Users/sindre/projects/experiments/react-dates"
    at /Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/sindre/projects/experiments/react-dates/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at /Users/sindre/projects/experiments/react-dates/node_modules/react-svg-loader/lib/loader.js:71:37
 @ ./src/components/DayPicker.jsx 43:18-51


ERROR in ./src/svg/arrow-left.svg
...

ERROR in ./src/svg/chevron-up.svg
...

ERROR in ./src/svg/close.svg
...

ERROR in ./src/svg/chevron-down.svg
...
```

**Comment by AdamEdgett** [comment]
Make sure you're on npm v3+
I believe that's what fixed this for me

**Comment by eMerzh** [comment]
i had also an issue at install time
```
$ npm install


npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Invalid name: "@kadira/storybook"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /test/react-dates/npm-debug.log
````

**Comment by AdamEdgett** [comment]
That may be because you have a custom npm registry set
see https://github.com/kadirahq/react-storybook/issues/15

**Comment by arunoda** [comment]
Actually we fixed this. This project use `@kadira/storybook` at 1.x.
If you upgrade this to `@kadira/storybook` to 2.x this issue will be gone.

**Comment by arunoda** [comment]
If not just use NPM3

**Comment by ljharb** [comment]
Certainly nobody anywhere should be using npm 1.x - if you're not on latest 2.x or 3.x of npm, you're going to have a bad time, and nobody should be supporting you :-)

**Comment by arunoda** [comment]
@ljharb I meant `@kadira/storybook` v1.x. Not NPM :)

**Comment by ljharb** [comment]
aha, gotcha

**Comment by ljharb** [comment]
Hopefully this is fixed by #9.

**Comment by eMerzh** [comment]
ok, change thing, but now at npm install i got

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Invalid name: "@kadira/react-split-pane"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /test/react-dates/npm-debug.log
```

**Comment by ljharb** [comment]
@eMerzh what's `npm config get registry` print out? If it's not `https://registry.npmjs.org/`, you might be pointing at an improperly-configured private registry.

**Comment by eMerzh** [comment]
$ npm config get registry
https://registry.npmjs.org/

**Comment by ljharb** [comment]
hmm, not sure what's going on there then. https://www.npmjs.com/package/@kadira/react-split-pane definitely exists. Maybe `rm -rf node_modules && npm install`?

**Comment by eMerzh** [comment]
mmh nope :/ didn't help ... i got no node_modules yet .... it's fresh after a clone

**Comment by ljharb** [comment]
@eMerzh and you're on the latest master as of tonight?

**Comment by eMerzh** [comment]
yes:
```
[10:16:05][bmaron@mbp /test]$ git clone https://github.com/airbnb/react-dates.git
Cloning into 'react-dates'...
remote: Counting objects: 203, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 203 (delta 16), reused 0 (delta 0), pack-reused 159
Receiving objects: 100% (203/203), 361.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (56/56), done.
Checking connectivity... done.
[10:16:05][bmaron@mbp /test]$ cd react-dates/
[10:16:05][bmaron@mbp /test/react-dates](master)$ npm install
(node:4703) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! Invalid name: "@kadira/storybook"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /test/react-dates/npm-debug.log
[10:16:05][bmaron@mbp /test]$ git rev-parse HEAD
ebc0fc87069d043786d45d83b71979881d435b79
```

**Comment by ljharb** [comment]
@eMerzh I can't conceive of why that doesn't work - that implies that your node and npm (both of which are very recent) can't handle scoped modules, which have been working for quite awhile now. I think I'd file an issue on npm itself for that.
