### ISSUE TITLE
Storyshots test falls

### ISSUE THREAD

**Issue by ArtyomResh** [airbnb/react-dates#528]
Hi, guys! :)

I need your help, please. On our project, we using jest + enzyme to test components. We created component Calendar, wich include DateRangePicker from your library, and its working fine in a storybook, but it fails in tests with an error message: 

```
TypeError: Cannot read property '__consolidated_events_handlers__' of null

      at addEventListener (node_modules/consolidated-events/lib/index.js:22:14)
      at CalendarMonthGrid.componentDidMount (node_modules/react-dates/lib/components/CalendarMonthGrid.js:254:70)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (node_modules/storyshots/dist/index.js:113:56)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

What am I doing wrong?

**Comment by ljharb** [comment]
Are you using `shallow`, `mount`? What's "storyshots" - is that some kind of snapshotting that perhaps is incorrectly faking a browser env?

**Comment by ArtyomResh** [comment]
Sorry, for not answering for so long, was busy.

**Comment by ljharb** [comment]
From the stack trace it seems like it's invoking componentDidMount without being in an actual browser - if so, it either needs to not do that, or it needs to correct the environment so it actually matches a browser.

**Comment by ArtyomResh** [comment]
Thank you, I will investigate that and update this post later.

**Comment by renanvalentin** [comment]
I'm having the same issue here. It seems that jsdom is not being setup properly:

https://gist.github.com/renanvalentin/eb0685f7a853f056383543d00b2b971f

**Comment by renanvalentin** [comment]
I've solved it by patching ReactDOM and ReactTestRenderer:
https://gist.github.com/renanvalentin/0472aa5ac4769ce5ec1b2f91f60e78fc
