### ISSUE TITLE
react-dates/initialize.js error when running (Jest) tests

### ISSUE THREAD

**Issue by apucacao** [airbnb/react-dates#854]
Hi all,

We just replaced our old date picker with this one and it's looking great! Thank you for all your hard work — we are very thankful!

Some of our unit tests around our components that use the date picker are failing with a strange error:

<details>
<summary>
Stacktrace from our component to DateInput
</summary>

```
|> yarn run test --no-cache --testPathPattern Clause-test.js
yarn run v1.1.0
$ jest "--no-cache" "--testPathPattern" "Clause-test.js"
 FAIL  static/ld/components/__tests__/Clause-test.js
  ● Test suite failed to run

    TypeError: (0 , _reactWithStyles.withStyles) is not a function

      at Object.65 (../../node_modules/react-dates/lib/components/DateInput.js:462:54)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateInput.js:21:30)
      at ../../node_modules/react-dates/lib/components/DateInput.js:67:18
      at Object.<anonymous> (../../node_modules/react-dates/lib/components/DateInput.js:70:10)
      at Object.34 (../../node_modules/react-dates/lib/components/DateRangePickerInput.js:333:18)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateRangePickerInput.js:21:30)
      at Object.67 (../../node_modules/react-dates/lib/components/DateRangePickerInput.js:401:18)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateRangePickerInput.js:21:30)
      at ../../node_modules/react-dates/lib/components/DateRangePickerInput.js:67:18
      at Object.<anonymous> (../../node_modules/react-dates/lib/components/DateRangePickerInput.js:70:10)
      at Object.54 (../../node_modules/react-dates/lib/components/DateRangePickerInputController.js:159:18)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateRangePickerInputController.js:21:30)
      at Object.68 (../../node_modules/react-dates/lib/components/DateRangePickerInputController.js:210:29)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateRangePickerInputController.js:21:30)
      at ../../node_modules/react-dates/lib/components/DateRangePickerInputController.js:67:18
      at Object.<anonymous> (../../node_modules/react-dates/lib/components/DateRangePickerInputController.js:70:10)
      at Object.<anonymous> (../../node_modules/react-dates/lib/components/DateRangePicker.js:256:18)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateRangePicker.js:21:30)
      at Object.<anonymous> (../../node_modules/react-dates/lib/components/DateRangePicker.js:348:39)
      at __webpack_require__ (../../node_modules/react-dates/lib/components/DateRangePicker.js:21:30)
      at ../../node_modules/react-dates/lib/components/DateRangePicker.js:67:18
      at Object.<anonymous> (../../node_modules/react-dates/lib/components/DateRangePicker.js:70:10)
      at Object.<anonymous> (../../node_modules/react-dates/index.js:1:112)
      at Object.<anonymous> (components/ui/dates/DateRangePicker.js:3:19)
      at Object.<anonymous> (components/ui/dates/index.js:1:188)
      at Object.<anonymous> (components/__tests__/Clause-test.js:7:14)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>
      at process._tickCallback (../../internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.033s
```
</details>

We're not sure what the cause is yet, but were hoping we've simply forgotten something obvious.  We tried modifying the source of `react-with-styles` with log statements but we've only been able to confirm that yes `withStyles` is `undefined`, even though the code looks fine.

We thought it might be related to `react-dates-initialize` being in the wrong place, but the UI actually loads and works well where it currently is.

Here are some relevant dependencies:

- React@^15.6.0
- Jest@21.2.1
- react-dates@14.0.0

Let me know if you need more information.

Thanks for reading!

**Comment by erin-doyle** [comment]
Where are you importing `react-dates-initialize`?  It may work fine where it is for running the entire app but perhaps is not in a good place for testing a specific module/component in the isolation of a unit test.

**Comment by apucacao** [comment]
Actually, I'm sorry, this was entirely our fault: our Jest `moduleNameMapper` (regex) was incorrectly mocking out `react-with-styles` 🤦‍♂️ 

Everything is working now!

Thanks.
